# Generated by Django 3.0.6 on 2020-10-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='five',
            new_name='five_star',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='four',
            new_name='four_star',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='one',
            new_name='one_star',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='three',
            new_name='three_star',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='two',
            new_name='two_star',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='zero',
            new_name='zero_star',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product_app.Product'),
        ),
    ]
